### ISSUE TITLE
Compatibility with original project

### ISSUE THREAD

**Issue by Lejo1** [est31/csrp-gmp#5]
Is this srp implementation(used for minetest) compatible with the [csrp](https://github.com/cocagne/csrp) implementation by cogagne? My main reason asking is, I wanted to use his python library [pysrp](https://github.com/cocagne/pysrp) when connecting to minetest servers.

Is that possible?

Or rather what are the changes?

Thanks!

**Comment by est31** [comment]
The master branch version of upstream csrp is not compatible with RFC 5054, but there is a branch that adds compatibility. See the note in their README.

This library has been made compatible to RFC 5054.

So it mostly depends on whether pysrp uses the RFC 5054 compatibility branch or master, but I fear it's master.

**Comment by est31** [comment]
Hmm seems that it can be enabled from python as well. See this note in the pysrp README:

> Note: RFC5054 now provides the de-facto standard for the hashing algorithm used for interoperable SRP implementations. When using pysrp to interact with another SRP implementation, use the srp.rfc5054_enable() method to enable RFC5054 compatibility.

**Comment by Lejo1** [comment]
I did some testing with this function srp.rfc5054_enable() and the two rfc5054 branches but they both didn't got it working...
As you have this correct test using the test vectors it's surly the problem of pysrp :(
